import type { Equipment, Movement, Service, Talent } from './types'

export const SEED_EQUIPMENT: Equipment[] = [
  { id:1, name:'ALEXA Mini LF 电影摄影机', brand:'ARRI', model:'Mini LF', cat:'cinema', code:'CAM-001', st:'in', own:'自有', val:320000, day:3800, dep:80000, tot:3, av:2, loc:'A-01', specs:['Large Format 4.5K','LPL / PL 卡口','14+ 档宽容度','ARRIRAW / ProRes'], note:'机身含手柄、CFast 卡仓与原厂箱，租用默认配 2 块 V 口电池。' },
  { id:2, name:'ALEXA 35 电影摄影机', brand:'ARRI', model:'ALEXA 35', cat:'cinema', code:'CAM-002', st:'in', own:'自有', val:380000, day:4200, dep:90000, tot:2, av:2, loc:'A-02', specs:['Super35 4.6K','LPL 卡口','17 档宽容度','EI 2560 双原生'], note:'旗舰机身，建议搭配 Master Prime 套装使用。' },
  { id:3, name:'V-RAPTOR 8K VV 电影摄影机', brand:'RED', model:'V-RAPTOR', cat:'cinema', code:'CAM-003', st:'out', own:'自有', val:260000, day:2800, dep:60000, tot:2, av:0, loc:'A-03', specs:['8K VV 全画幅','RF / PL 卡口','8K 120fps','REDCODE RAW'], note:'当前两台均在外借项目，预计本周五归还。' },
  { id:4, name:'VENICE 2 电影摄影机', brand:'Sony', model:'VENICE 2', cat:'cinema', code:'CAM-004', st:'reserved', own:'自有', val:290000, day:3200, dep:70000, tot:1, av:1, loc:'A-04', specs:['8.6K 全画幅','双原生 ISO','内录 X-OCN','PL / E 卡口'], note:'已被网剧项目预留，可协调档期。' },
  { id:5, name:'URSA Cine 12K 电影摄影机', brand:'Blackmagic', model:'URSA Cine', cat:'cinema', code:'CAM-005', st:'in', own:'自有', val:150000, day:1600, dep:30000, tot:1, av:1, loc:'A-05', specs:['12K RGBW','内置 8TB','PL / EF / LPL','Blackmagic RAW'], note:'' },
  { id:6, name:'FX9 全画幅摄影机', brand:'Sony', model:'FX9', cat:'cinema', code:'CAM-006', st:'in', own:'自有', val:80000, day:900, dep:15000, tot:3, av:3, loc:'A-06', specs:['全画幅 6K 传感器','双原生 ISO','E 卡口','S-Cinetone'], note:'适合纪录片与采访场景。' },
  { id:7, name:'FX6 全画幅摄影机', brand:'Sony', model:'FX6', cat:'cinema', code:'CAM-007', st:'in', own:'合作商', val:38000, day:650, dep:10000, tot:4, av:3, loc:'A-07', specs:['全画幅 4K 120p','可变 ND','E 卡口','轻便机身'], note:'合作商挂靠设备，结算按合作价。' },
  { id:8, name:'Master Prime 定焦镜头套装', brand:'ARRI / ZEISS', model:'Master Prime', cat:'lens', code:'LEN-001', st:'in', own:'自有', val:600000, day:2600, dep:60000, tot:1, av:1, loc:'B-01', specs:['16/25/35/50/85mm','T1.3 大光圈','PL 卡口','整套防潮箱'], note:'套装六支，租用需登记并由设备组随行。' },
  { id:9, name:'S7/i 全画幅定焦套装', brand:'Cooke', model:'S7/i FF', cat:'lens', code:'LEN-002', st:'in', own:'自有', val:700000, day:2400, dep:60000, tot:1, av:1, loc:'B-02', specs:['25/32/40/50/75mm','T2.0','Cooke Look','/i 元数据'], note:'' },
  { id:10, name:'CN-E 电影定焦套装', brand:'Canon', model:'CN-E', cat:'lens', code:'LEN-003', st:'in', own:'自有', val:180000, day:1200, dep:25000, tot:1, av:1, loc:'B-03', specs:['24/35/50/85mm','T1.5','EF 卡口','性价比之选'], note:'' },
  { id:11, name:'Vespid 全画幅定焦套装', brand:'DZOFilm', model:'Vespid', cat:'lens', code:'LEN-004', st:'in', own:'合作商', val:60000, day:700, dep:12000, tot:2, av:2, loc:'B-04', specs:['全画幅覆盖','T2.1','PL / EF 可换','轻量'], note:'合作商挂靠。' },
  { id:12, name:'EZ 电影变焦镜头', brand:'Angénieux', model:'EZ-1/2', cat:'lens', code:'LEN-005', st:'repair', own:'自有', val:130000, day:1100, dep:22000, tot:2, av:1, loc:'B-05', specs:['可换后组','S35 / FF','变焦比 3x','法版工艺'], note:'其中一支镜头送检维修中。' },
  { id:13, name:'探针 / 微距镜头', brand:'Laowa', model:'Probe', cat:'lens', code:'LEN-006', st:'in', own:'自有', val:20000, day:400, dep:6000, tot:2, av:2, loc:'B-06', specs:['24mm 探针','2:1 微距','可防水','广告特写'], note:'适合产品与美食微距镜头。' },
  { id:14, name:'SkyPanel S60-C 柔光灯', brand:'ARRI', model:'S60-C', cat:'light', code:'LIT-001', st:'in', own:'自有', val:60000, day:800, dep:12000, tot:4, av:3, loc:'C-01', specs:['RGBW LED','2800-10000K','450W','含柔光格栅'], note:'' },
  { id:15, name:'LS 600x Pro 聚光灯', brand:'Aputure', model:'600x Pro', cat:'light', code:'LIT-002', st:'in', own:'自有', val:12000, day:360, dep:4000, tot:6, av:5, loc:'C-02', specs:['双色温','600W','Bowens 卡口','防雨'], note:'常用主光，库存充足。' },
  { id:16, name:'Nova P600c 柔光板', brand:'Aputure', model:'P600c', cat:'light', code:'LIT-003', st:'in', own:'自有', val:18000, day:420, dep:5000, tot:3, av:3, loc:'C-03', specs:['RGBWW 面光','600W','内置电池仓','超薄'], note:'' },
  { id:17, name:'Titan Tube 灯管套装(8 支)', brand:'Astera', model:'Titan Tube', cat:'light', code:'LIT-004', st:'reserved', own:'自有', val:40000, day:600, dep:8000, tot:2, av:1, loc:'C-04', specs:['8 支套装','无线 CRMX','内置电池','像素映射'], note:'一套已预留给直播项目。' },
  { id:18, name:'M18 HMI 镝灯', brand:'ARRI', model:'M18', cat:'light', code:'LIT-005', st:'in', own:'合作商', val:50000, day:700, dep:10000, tot:2, av:2, loc:'C-05', specs:['1800W HMI','日光色温','含镇流器','高亮硬光'], note:'合作商挂靠设备。' },
  { id:19, name:'RR Rainbow 灯管套装', brand:'Quasar', model:'RR Rainbow', cat:'light', code:'LIT-006', st:'in', own:'自有', val:16000, day:300, dep:4000, tot:4, av:4, loc:'C-06', specs:['RGBX 灯管','多规格','DMX 控制','氛围光'], note:'' },
  { id:20, name:'Cine 7 监视器', brand:'SmallHD', model:'Cine 7', cat:'monitor', code:'MON-001', st:'in', own:'自有', val:18000, day:300, dep:4000, tot:4, av:3, loc:'D-01', specs:['7" 1800nit','SDI / HDMI','LUT / 波形','可装电池'], note:'' },
  { id:21, name:'1303 HDR 导演监视器', brand:'SmallHD', model:'1303 HDR', cat:'monitor', code:'MON-002', st:'in', own:'自有', val:40000, day:500, dep:8000, tot:2, av:2, loc:'D-02', specs:['13" 1500nit','HDR 预览','多画面','导演村'], note:'' },
  { id:22, name:'LVM-171S 监看监视器', brand:'TVLogic', model:'LVM-171S', cat:'monitor', code:'MON-003', st:'in', own:'自有', val:30000, day:400, dep:6000, tot:2, av:2, loc:'D-03', specs:['17" 广色域','调色级','SDI','机房监看'], note:'' },
  { id:23, name:'Shogun 7 录机监视器', brand:'Atomos', model:'Shogun 7', cat:'monitor', code:'MON-004', st:'inspect', own:'自有', val:12000, day:220, dep:3000, tot:3, av:2, loc:'D-04', specs:['7" HDR','ProRes RAW','SDI / HDMI','录监一体'], note:'一台归库待检查。' },
  { id:24, name:'Video 18 流体云台脚架', brand:'Sachtler', model:'Video 18', cat:'support', code:'SUP-001', st:'in', own:'自有', val:30000, day:280, dep:4000, tot:4, av:4, loc:'E-01', specs:['承重 2-22kg','碳纤脚管','流体阻尼','含云台'], note:'' },
  { id:25, name:'Ronin 2 专业稳定器', brand:'DJI', model:'Ronin 2', cat:'support', code:'SUP-002', st:'in', own:'自有', val:40000, day:600, dep:10000, tot:2, av:2, loc:'E-02', specs:['承重 13.6kg','车载 / 飞行','含配件箱','专业级'], note:'' },
  { id:26, name:'RS 4 Pro 手持稳定器', brand:'DJI', model:'RS 4 Pro', cat:'support', code:'SUP-003', st:'out', own:'自有', val:6000, day:200, dep:3000, tot:5, av:2, loc:'E-03', specs:['承重 4.5kg','碳纤臂','LiDAR 对焦','手持'], note:'三台外借中。' },
  { id:27, name:'2575 D 专业云台', brand:"O'Connor", model:'2575 D', cat:'support', code:'SUP-004', st:'in', own:'合作商', val:90000, day:700, dep:12000, tot:1, av:1, loc:'E-04', specs:['顶级流体头','无级阻尼','重负载','合作商'], note:'合作商挂靠。' },
  { id:28, name:'C-Stand 灯架套装(10 支)', brand:'Matthews', model:'C-Stand', cat:'support', code:'SUP-005', st:'in', own:'自有', val:12000, day:150, dep:1500, tot:1, av:1, loc:'E-05', specs:['10 支套装','含旗板臂','沙袋配套','灯位必备'], note:'按套出租。' },
  { id:29, name:'Dana Dolly 轨道套装', brand:'Dana', model:'Dana Dolly', cat:'support', code:'SUP-006', st:'in', own:'自有', val:20000, day:350, dep:5000, tot:1, av:1, loc:'E-06', specs:['便携轨道','可调轮距','含轨道管','移动镜头'], note:'' },
  { id:30, name:'888 多通道调音台', brand:'Sound Devices', model:'888', cat:'audio', code:'AUD-001', st:'in', own:'自有', val:60000, day:700, dep:10000, tot:1, av:1, loc:'F-01', specs:['8 路输入','32-bit 浮点','内置时码','现场混录'], note:'' },
  { id:31, name:'MKH 416 指向性枪麦', brand:'Sennheiser', model:'MKH 416', cat:'audio', code:'AUD-002', st:'in', own:'自有', val:8000, day:150, dep:2000, tot:3, av:3, loc:'F-02', specs:['超心型','抗潮湿','行业标准','含防风'], note:'' },
  { id:32, name:'MTP60 无线话筒套装', brand:'Wisycom', model:'MTP60', cat:'audio', code:'AUD-003', st:'in', own:'合作商', val:90000, day:600, dep:12000, tot:2, av:2, loc:'F-03', specs:['宽频无线','多通道','低延迟','合作商'], note:'合作商挂靠。' },
  { id:33, name:'F8n Pro 现场录音机', brand:'Zoom', model:'F8n Pro', cat:'audio', code:'AUD-004', st:'in', own:'个人挂靠', val:8000, day:200, dep:2500, tot:2, av:2, loc:'F-04', specs:['8 输入','32-bit','双 SD','含时码'], note:'个人挂靠设备。' },
  { id:34, name:'Avata 2 穿越机套装', brand:'DJI', model:'Avata 2', cat:'fpv', code:'FPV-001', st:'in', own:'自有', val:8000, day:350, dep:4000, tot:3, av:3, loc:'G-01', specs:['Cinewhoop','O4 高清图传','约 23min','含眼镜遥控'], note:'即开即飞，适合室内穿梭。' },
  { id:35, name:'5 寸自组穿越机', brand:'Custom', model:'5" FPV', cat:'fpv', code:'FPV-002', st:'in', own:'个人挂靠', val:6000, day:300, dep:3000, tot:4, av:4, loc:'G-02', specs:['5 寸轴距','高清数字图传','极速机动','需专业飞手'], note:'个人挂靠，建议搭配飞手服务。' },
  { id:36, name:'Cinewhoop 室内穿越机', brand:'Custom', model:'Cinewhoop', cat:'fpv', code:'FPV-003', st:'reserved', own:'自有', val:9000, day:380, dep:4000, tot:2, av:1, loc:'G-03', specs:['涵道保护','室内安全','稳定运镜','含护栏'], note:'一台已预留。' },
  { id:37, name:'穿越机飞手套装', brand:'DJI', model:'Goggles 3', cat:'fpv', code:'FPV-004', st:'in', own:'自有', val:9000, day:250, dep:3000, tot:2, av:2, loc:'G-04', specs:['Goggles 3 眼镜','RC 遥控','高清回传','配套使用'], note:'眼镜 + 遥控套装。' },
  { id:38, name:'Inspire 3 专业航拍无人机', brand:'DJI', model:'Inspire 3', cat:'drone', code:'DRN-001', st:'out', own:'自有', val:110000, day:2200, dep:30000, tot:2, av:1, loc:'H-01', specs:['全画幅 8K','DL 卡口','15km O3 Pro','双控'], note:'需持证飞手，一台外借。' },
  { id:39, name:'Mavic 3 Cine 航拍无人机', brand:'DJI', model:'Mavic 3 Cine', cat:'drone', code:'DRN-002', st:'in', own:'自有', val:28000, day:800, dep:10000, tot:3, av:2, loc:'H-02', specs:['4/3 CMOS','Apple ProRes','5.1K 50fps','便携'], note:'' },
  { id:40, name:'Air 3 航拍无人机', brand:'DJI', model:'Air 3', cat:'drone', code:'DRN-003', st:'in', own:'合作商', val:12000, day:500, dep:5000, tot:4, av:4, loc:'H-03', specs:['双摄','4K 100fps','46min 续航','轻巧'], note:'合作商挂靠。' },
  { id:41, name:'V-Mount 电池套装', brand:'Core SWX', model:'V-Mount', cat:'accessory', code:'ACC-001', st:'in', own:'自有', val:30000, day:200, dep:3000, tot:10, av:8, loc:'I-01', specs:['多块装','D-tap 输出','含充电器','大容量'], note:'按套出租。' },
  { id:42, name:'Nucleus-M 无线跟焦', brand:'Tilta', model:'Nucleus-M', cat:'accessory', code:'ACC-002', st:'in', own:'自有', val:12000, day:250, dep:4000, tot:3, av:3, loc:'I-02', specs:['三马达','无线手轮','低延迟','含支架'], note:'' },
  { id:43, name:'Bolt 6 LT 无线图传', brand:'Teradek', model:'Bolt 6 LT', cat:'accessory', code:'ACC-003', st:'in', own:'自有', val:40000, day:450, dep:8000, tot:2, av:2, loc:'I-03', specs:['零延迟','750ft','多接收','5GHz'], note:'' },
  { id:44, name:'CFexpress / SSD 存储套装', brand:'Angelbird', model:'Storage', cat:'accessory', code:'ACC-004', st:'in', own:'自有', val:30000, day:300, dep:5000, tot:6, av:5, loc:'I-04', specs:['多卡组合','高速读写','含读卡器','含硬盘箱'], note:'按套出租，归还需清空数据。' },
  { id:45, name:'电影滤镜套装', brand:'NiSi', model:'Cine Filter', cat:'accessory', code:'ACC-005', st:'in', own:'合作商', val:20000, day:200, dep:3000, tot:3, av:3, loc:'I-05', specs:['ND / 黑柔','多尺寸','含滤镜包','合作商'], note:'合作商挂靠。' },
  { id:46, name:'Delta Pro 移动电站', brand:'EcoFlow', model:'Delta Pro', cat:'accessory', code:'ACC-006', st:'in', own:'自有', val:25000, day:300, dep:4000, tot:4, av:3, loc:'I-06', specs:['3.6kWh','市电级输出','快充','外景供电'], note:'外景常备电源。' },
]

export const SEED_MOVEMENTS: Movement[] = [
  { id:'L0', t:'今天 14:20', dev:'RED V-RAPTOR 8K VV', op:'出库', by:'张磊', proj:'某汽车品牌 TVC' },
  { id:'L1', t:'今天 11:05', dev:'DJI Inspire 3', op:'出库', by:'李娜', proj:'城市形象宣传片' },
  { id:'L2', t:'昨天 18:40', dev:'Aputure LS 600x Pro ×2', op:'入库', by:'王浩', proj:'直播多机位' },
  { id:'L3', t:'昨天 16:12', dev:'Angénieux EZ 变焦', op:'报修', by:'设备组', proj:'例行检修' },
  { id:'L4', t:'昨天 09:30', dev:'Sony VENICE 2', op:'预留', by:'陈曦', proj:'网剧 第二季' },
  { id:'L5', t:'06-13 20:15', dev:'DJI RS 4 Pro ×3', op:'出库', by:'刘洋', proj:'美食短视频' },
]

export const SEED_TALENT: Talent[] = [
  { id:'t1', name:'林深', initials:'林', role:'摄影指导 DP', roleKey:'dp', years:12, color:'oklch(0.52 0.12 258)',
    specialty:'高质感品牌广告与情绪叙事', skills:['大画幅影像','运动镜头','自然光塑造','广告叙事'], gear:['ALEXA 35','Master Prime','VENICE 2'],
    bio:'从业十二年的摄影指导，专注高端汽车与品牌广告，作品以克制的光影和扎实的运动镜头见长，与多家 4A 与品牌方长期合作。',
    projects:[{name:'某新能源汽车 全球发布片',year:'2025',role:'摄影指导'},{name:'国际美妆品牌 形象 TVC',year:'2024',role:'摄影指导'},{name:'城市形象片《晨光》',year:'2024',role:'摄影指导'}] },
  { id:'t2', name:'周屿', initials:'周', role:'航拍飞手', roleKey:'aerial', years:9, color:'oklch(0.54 0.11 232)',
    specialty:'大场景航拍与跟车追拍', skills:['Inspire 3 操控','跟车航拍','编队飞行','AOPA 持证'], gear:['DJI Inspire 3','Mavic 3 Cine','Air 3'],
    bio:'AOPA 持证飞手，九年航拍经验，擅长复杂环境下的跟车与大场景调度，多次完成高速公路、山地与城市夜景的高难度航拍。',
    projects:[{name:'汽车品牌 公路跟拍片',year:'2025',role:'航拍'},{name:'山地旅游 宣传片',year:'2024',role:'航拍'},{name:'大型活动 开幕航拍',year:'2023',role:'航拍'}] },
  { id:'t3', name:'苏越', initials:'苏', role:'FPV 穿越机飞手', roleKey:'fpv', years:5, color:'oklch(0.55 0.13 150)',
    specialty:'高速穿梭与室内一镜到底', skills:['室内穿越','一镜到底','自组穿越机','极限机动'], gear:['DJI Avata 2','5寸自组机','Cinewhoop'],
    bio:'新生代 FPV 飞手，自组与调试穿越机，擅长室内一镜到底与工业场景穿梭运镜，为广告与空间展示提供独特视角。',
    projects:[{name:'餐饮空间 一镜到底',year:'2025',role:'FPV'},{name:'工厂产线 穿越片',year:'2024',role:'FPV'},{name:'酒店开业 穿梭宣传',year:'2024',role:'FPV'}] },
  { id:'t4', name:'高远', initials:'高', role:'稳定器操作', roleKey:'rig', years:10, color:'oklch(0.50 0.10 210)',
    specialty:'长镜头调度与车载拍摄', skills:['Ronin 2','斯坦尼康','长镜头调度','车载拍摄'], gear:['DJI Ronin 2','RS 4 Pro',"O'Connor 2575"],
    bio:'十年稳定器与斯坦尼康操作经验，擅长复杂走位的长镜头一次成型，是动态广告与活动现场的可靠运镜搭档。',
    projects:[{name:'汽车 棚内环绕片',year:'2025',role:'稳定器'},{name:'品牌 一镜到底广告',year:'2024',role:'斯坦尼康'},{name:'演唱会 跟拍',year:'2023',role:'稳定器'}] },
  { id:'t5', name:'何晚', initials:'何', role:'灯光指导', roleKey:'light', years:11, color:'oklch(0.57 0.12 70)',
    specialty:'影棚布光与氛围光塑造', skills:['影棚布光','大场景照明','氛围光','HMI 硬光'], gear:['SkyPanel S60-C','Nova P600c','M18 HMI'],
    bio:'十一年灯光经验，从棚内静物到大场景外景皆能掌控，以精准的氛围光和质感塑造为画面注入电影感。',
    projects:[{name:'美妆 TVC 棚拍',year:'2025',role:'灯光指导'},{name:'汽车 夜景广告',year:'2024',role:'灯光指导'},{name:'纪录片 自然光补光',year:'2023',role:'灯光指导'}] },
  { id:'t6', name:'沈淮', initials:'沈', role:'调色师', roleKey:'color', years:8, color:'oklch(0.50 0.12 300)',
    specialty:'广告调性与胶片仿真', skills:['DaVinci Resolve','HDR 调色','广告调性','胶片仿真'], gear:['DaVinci 调色台','TVLogic 监视器'],
    bio:'八年调色经验，擅长为品牌定制专属色彩调性，HDR 与胶片仿真俱佳，让成片在不同平台都保持统一观感。',
    projects:[{name:'多支 汽车广告 调色',year:'2025',role:'调色'},{name:'院线 短片调色',year:'2024',role:'调色'},{name:'时尚大片 调色',year:'2024',role:'调色'}] },
  { id:'t7', name:'陆风', initials:'陆', role:'录音师', roleKey:'audio', years:9, color:'oklch(0.52 0.10 145)',
    specialty:'同期录音与现场混音', skills:['同期录音','无线话筒','现场混音','时码同步'], gear:['Sound Devices 888','MKH 416','Wisycom MTP60'],
    bio:'九年现场录音经验，擅长复杂环境下的同期收音与多路无线管理，为活动与访谈提供干净可靠的声音素材。',
    projects:[{name:'大型论坛 现场收音',year:'2025',role:'录音'},{name:'访谈纪录片 同期',year:'2024',role:'录音'},{name:'综艺 多机位收音',year:'2023',role:'录音'}] },
  { id:'t8', name:'顾辰', initials:'顾', role:'AI 视觉设计师', roleKey:'ai', years:4, color:'oklch(0.52 0.13 318)',
    specialty:'AI 分镜与虚拟影像生成', skills:['AI 分镜生成','数字人','风格迁移','虚拟场景'], gear:['Stable Diffusion','Runway','Nuke 合成'],
    bio:'融合 AI 生成与传统后期的视觉设计师，擅长用 AI 快速产出分镜与概念影像，并将其与实拍无缝合成。',
    projects:[{name:'品牌 AI 概念片',year:'2025',role:'AI 视觉'},{name:'数字人 口播项目',year:'2024',role:'AI 视觉'},{name:'虚拟场景 广告',year:'2024',role:'合成'}] },
  { id:'t9', name:'江岚', initials:'江', role:'导演 / 创意', roleKey:'director', years:13, color:'oklch(0.50 0.11 35)',
    specialty:'广告创意与现场调度', skills:['广告创意','分镜设计','现场调度','品牌叙事'], gear:['创意统筹','分镜脚本'],
    bio:'十三年广告导演经验，从创意提案到现场执行全流程把控，以清晰的品牌叙事和高效的现场调度著称。',
    projects:[{name:'新能源汽车 发布片',year:'2025',role:'导演'},{name:'美妆品牌 系列 TVC',year:'2024',role:'导演'},{name:'城市形象 宣传片',year:'2023',role:'导演'}] },
]

export const SEED_SERVICES: Service[] = [
  { id:'s1', name:'专业航拍服务包', domain:'aerial', tagline:'空中视角，一镜入魂', priceFrom:18000, unit:'天', duration:'1–3 天', crew:3,
    hw:[{label:'航拍无人机',detail:'DJI Inspire 3（8K）/ Mavic 3 Cine / Air 3'},{label:'FPV 穿越机',detail:'Avata 2 / 5 寸自组机（室内一镜到底）'},{label:'镜头组',detail:'DL 18 / 24 / 35 / 50mm 全焦段'}],
    caps:['跟车追拍与公路大场景','建筑 / 地貌俯瞰揭示','室内 FPV 一镜到底','编队灯光夜景','螺旋上升揭示运镜'],
    deliver:['4K / 8K 航拍原片','调色成片','30s 精剪版'], talent:['t2','t3','t1'],
    desc:'以航拍无人机 + FPV 穿越机双线配置，覆盖从万米大场景到室内穿梭的全维度空中视角，适合汽车、文旅、城市形象等需要恢弘画面的项目。' },
  { id:'s2', name:'汽车广告拍摄包', domain:'auto', tagline:'让金属也有呼吸感', priceFrom:38000, unit:'天', duration:'2–4 天', crew:6,
    hw:[{label:'电影机',detail:'ALEXA 35 / VENICE 2'},{label:'镜头',detail:'Master Prime 定焦套装'},{label:'运动设备',detail:'跟车炮台 + Ronin 2 + 灯光车'}],
    caps:['跟车动态拍摄','棚内转盘环绕','流体运镜','局部金属特写','夜景光绘'],
    deliver:['正片 + 多版本剪辑','车型特写素材库','调色成片'], talent:['t1','t4','t5','t2'],
    desc:'专为汽车影像打造的高配置服务包，电影机 + 顶级定焦 + 跟车炮台，配合资深摄影、灯光与航拍团队，呈现金属质感与速度张力。' },
  { id:'s3', name:'TVC / 动态影像包', domain:'motion', tagline:'为品牌讲一个故事', priceFrom:32000, unit:'天', duration:'2–5 天', crew:7,
    hw:[{label:'电影机',detail:'VENICE 2 / ALEXA Mini LF'},{label:'镜头',detail:'Cooke S7/i 全画幅定焦'},{label:'灯光',detail:'SkyPanel + 移动轨道'}],
    caps:['情绪化叙事','高速慢动作','产品微距','棚拍合成','大场景调度'],
    deliver:['品牌主片','15s / 30s 投放版','拍摄花絮'], talent:['t9','t1','t5','t6'],
    desc:'从创意分镜到成片交付的一站式品牌影像服务，导演 + 摄影 + 灯光 + 调色全链路，适合产品上新、品牌形象与节点营销。' },
  { id:'s4', name:'活动 / 现场拍摄包', domain:'event', tagline:'不错过每一个高光时刻', priceFrom:12000, unit:'天', duration:'1–2 天', crew:5,
    hw:[{label:'多机位',detail:'Sony FX9 ×3 多机位'},{label:'传输',detail:'Teradek 无线图传'},{label:'收音',detail:'枪麦 + 无线话筒套装'}],
    caps:['多机位实时切换','直播导播','当日快剪交付','嘉宾采访','航拍全景'],
    deliver:['活动全程记录','精剪集锦','直播信号'], talent:['t7','t4','t2'],
    desc:'面向发布会、论坛、演出等现场的多机位拍摄包，支持直播导播与当日快剪，确保每个高光瞬间被专业记录。' },
  { id:'s5', name:'课件 / 知识影像包', domain:'course', tagline:'让专业被清晰看见', priceFrom:6800, unit:'天', duration:'按量', crew:3,
    hw:[{label:'摄影机',detail:'Sony FX6 ×2 双机位'},{label:'辅助',detail:'提词器 + 影棚柔光'},{label:'收音',detail:'领夹 + 录音棚环境'}],
    caps:['双机位讲解拍摄','绿幕抠像','PPT / 板书合成','提词录制','章节化交付'],
    deliver:['成套课件视频','字幕版本','封面图'], talent:['t5','t7','t6'],
    desc:'为知识付费、企业培训与教学机构定制的高性价比影像包，标准化布光与收音，批量产出清晰专业的课件视频。' },
  { id:'s6', name:'AI 制作 / 虚拟影像包', domain:'ai', tagline:'用 AI 扩展想象的边界', priceFrom:9800, unit:'项', duration:'3–7 天', crew:3,
    hw:[{label:'实拍',detail:'绿幕棚 + 动捕（按需）'},{label:'AI 管线',detail:'SD / Runway / 数字人生成'},{label:'合成',detail:'Nuke / AE 合成管线'}],
    caps:['AI 分镜生成','数字人口播','风格迁移','虚拟场景搭建','概念预演'],
    deliver:['AI 成片','可迭代工程文件','分镜资产'], talent:['t8','t9','t6'],
    desc:'结合实拍与 AI 生成的新型影像服务，快速产出概念片、数字人与虚拟场景，适合预算有限或需要超现实表达的项目。' },
]
